trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: dev-vars

steps:

# Checkout Source Code
- checkout: self

# Display Variables
- script: |
    echo "Environment: $(ENV)"
    echo "Application Name: $(APP_NAME)"
  displayName: 'Print Variables'

# Install Java
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
  displayName: 'Install JDK 17'

# Maven Build
- task: Maven@4
  displayName: 'Maven Clean Package'
  inputs:
    mavenPomFile: 'javaapp/pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'

# Copy Artifact
- task: CopyFiles@2
  displayName: 'Copy JAR File'
  inputs:
    SourceFolder: 'javaapp/target'
    Contents: '*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# Publish Artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifact'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'java-artifact'
    publishLocation: 'Container'