trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'target'
    artifactName: 'java-artifact'