trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'javaapp/pom.xml'
    goals: 'clean package'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'javaapp/target'
    artifactName: 'java-artifact'