name: JavaAPP

on:
  pull_request:
    branches: [ "master" ]

  push:
    branches: [ "master" ]

permissions:
  contents: read

env:
  APP_NAME: javaapp
  RESOURCE_GROUP: test-rg
  VM_NAME: vm2

jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build + Test
        run: mvn clean package test


  deploy:
    needs: build-test
    runs-on: ubuntu-latest

    environment:
      name: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy on Azure VM
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az vm run-command invoke \
              --resource-group test-rg \
              --name vm2 \
              --command-id RunShellScript \
              --scripts "
                cd /home/azureuser/java-app || exit 1

                git pull || true

                mvn clean package

                docker stop javaapp || true
                docker rm javaapp || true

                docker build -t javaapp:latest .

                docker run -d -p 8080:8080 --name javaapp javaapp:latest
              "