name: "Reusable - task-group1"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      working-directory:
        required: false
        type: string
        default: '.'

jobs:
  run-task-group:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4

